### Matrix oprerations

In [4]:
import numpy as np

In [7]:
p=np.array([[1,7],[2,1],[3,2]])
print(p)

[[1 7]
 [2 1]
 [3 2]]


In [8]:
q=np.array([[1,1],[1,-1],[1,0]])
print(q)

[[ 1  1]
 [ 1 -1]
 [ 1  0]]


In [9]:
c1=np.add(p,q)
print(c1)

[[2 8]
 [3 0]
 [4 2]]


In [10]:
c2=np.subtract(p,q)
print(c2)

[[0 6]
 [1 2]
 [2 2]]


In [11]:
r=np.array([[1,3,1],[1,0,1]])
print(r)

[[1 3 1]
 [1 0 1]]


In [12]:
c2=np.dot(p,r)
print(c2)

[[8 3 8]
 [3 6 3]
 [5 9 5]]


In [13]:
det=np.linalg.det(c2)
print(det)

0.0


In [14]:
s2=np.linalg.inv(c2)

LinAlgError: Singular matrix

In [15]:
M=np.array([[1,-1],[2,3]])
print(M)

[[ 1 -1]
 [ 2  3]]


In [16]:
inv=np.linalg.inv(M)
print(inv)

[[ 0.6  0.2]
 [-0.4  0.2]]


### if you multiply matrix and its inverse then you will get an identity matrix

In [17]:
print(np.dot(M,inv))

[[ 1.00000000e+00 -5.55111512e-17]
 [ 1.11022302e-16  1.00000000e+00]]


### Eigenvaluues and Eigenvectors

In [25]:
A=np.array([[2,-2,3],[1,1,1],[1,3,-1]])
print(A)

[[ 2 -2  3]
 [ 1  1  1]
 [ 1  3 -1]]


In [26]:
evalues, evectors=np.linalg.eig(A)

In [27]:
print(evalues)

[ 3.  1. -2.]


In [28]:
print(evectors)

[[ 0.57735027  0.57735027 -0.61684937]
 [ 0.57735027 -0.57735027 -0.05607722]
 [ 0.57735027 -0.57735027  0.78508102]]


In [30]:
res=np.multiply(A,evectors[0])
print(res)

[[ 1.15470054 -1.15470054 -1.85054811]
 [ 0.57735027  0.57735027 -0.61684937]
 [ 0.57735027  1.73205081  0.61684937]]
