### Spectral decomposition

In most of the problems we obtain the co-variance matrix and then do SVD. The nice thing about the co-variance matrix is that it is a symmetric and will always have the eigen decomposition.

In [2]:
import numpy as np

In [5]:
np.set_printoptions(precision=4, suppress=True)

We will take a 3x4 matrix for to calculate the SVD

In [7]:
a=np.array([[1,2,3,4],[1,1,2,3],[0,1,1,0]])
print(a)

[[1 2 3 4]
 [1 1 2 3]
 [0 1 1 0]]


Max rank of the above matrix can be 3 and there can be max 3 singular values

In [10]:
u,s,vh = np.linalg.svd(a, full_matrices=True)
print(u.shape,s.shape,vh.shape)

(3, 3) (3,) (4, 4)


In [11]:
print(u.dot(u.T))

[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]


In the above statement we are checking that u is a orthogonal matrix. so if you multiply a orthogonal matrix with it's transpose then you will get an Identity matrix. Shape property is holds the shape of the matrix.

Now we need to make s a 3x4 matrix. Since S is a given simply as a 3 element numpy array, we need to reshape it into a 3x4 array with the 3 elements along it's diagonal

In [12]:
sd=np.diag(s)
print(sd)

[[6.7509 0.     0.    ]
 [0.     1.1734 0.    ]
 [0.     0.     0.2186]]


In [13]:
b=np.zeros((3,4))
b[:,:-1]=sd
print(b)

[[6.7509 0.     0.     0.    ]
 [0.     1.1734 0.     0.    ]
 [0.     0.     0.2186 0.    ]]


Now we have u, sigma and v transpose then let's apply the svd formula and reconstruct the matrix

In [16]:
svdr=np.dot(np.dot(u,b),vh)
print(svdr)

[[ 1.  2.  3.  4.]
 [ 1.  1.  2.  3.]
 [ 0.  1.  1. -0.]]


Now we have the same matrix that proves the svd formula that A=uxsigmaxvT

Now, Let's calculate the 2 rank apprximation the matrix A

so, 2 rank approximation can be made by making the 3rd singular value as zero.

In [17]:
ns=[s[0],s[1],0]
print(ns)

[6.7509429737293525, 1.1734412499397089, 0]


In [19]:
sd=np.diag(ns)
print(sd)

[[6.7509 0.     0.    ]
 [0.     1.1734 0.    ]
 [0.     0.     0.    ]]


In [20]:
b=np.zeros((3,4))
b[:,:-1]=sd
print(b)

[[6.7509 0.     0.     0.    ]
 [0.     1.1734 0.     0.    ]
 [0.     0.     0.     0.    ]]


In [21]:
svdr=np.dot(np.dot(u,b),vh)
print(svdr)

[[ 1.096   1.9567  3.0526  3.9542]
 [ 0.8764  1.0558  1.9322  3.0589]
 [-0.0559  1.0252  0.9693  0.0267]]
